$(function () {
  $(".btn__submit").on('click', function () {
    const FamilyName = $("#family__name").val();
    console.log("名字");
    console.log(FamilyName);
    const GivenName = $("#given__name").val();
    console.log("名前");
    console.log(GivenName);
    const LabelSection = $(":checked").val();
    console.log("生年月日");
    console.log(LabelSection);
    console.log("年");
    const SelectUnit = $('select__unit[name=.month]:checked').val();
    console.log(SelectUnit);
    console.log("月");
    console.log("日");
    const AccountName = $("#account__name").val();
    console.log("アカウント情報");
    console.log("アカウント名");
    console.log(AccountName);
    const Email = $("#email").val();
    console.log("メールアドレス");
    console.log(Email);
    const PassWord = $("#password").val();
    console.log("パスワード");
    console.log(PassWord);
    const DuplicationPassword = $("#duplication__password").val();
    console.log("確認用パスワード");
    console.log(DuplicationPassword);
    const ContentTitle = $("#content__title").val();
    console.log("名字");
    console.log(ContentTitle);
    const Address = $("#address").val();
    console.log("住所");
    console.log(address);
    const Tel = $("#tel").val();
    console.log("電話番号");
    console.log(Tel);
  });
});